### PR TITLE
New API

### PR DESCRIPTION
**Pull request by dafuga**

### CODE REVIEW

**Comment by aaroncox** [comment]
Two output contracts: 

```
contracts/rewards.gm.ts
test/tmp/rewards.gm.ts
```

**Comment by dafuga** [comment]
Good catch! `contracts/rewards.gm.ts` was a contract example that I added a while back, I just removed it.

**Comment by dafuga** [comment]
The reason why I decided to make the contract object a constructor param is because the table class actually uses three different values which will already be defined in any contract object (contract name, client and ABI). To me, it feels cleaner to just pass a contract object rather than those 3 values.

**Comment by aaroncox** [comment]
It makes sense, it just places a requirement on instantiating a `Table` instance to already have a `Contract` instance, which limits flexibility. If we had it where you passed those 3 things independently, developers who wanted could instantiate a `Table` to do querying against without needing a `Contract` instance.

Originally I had a reason for not wanting to pass in the entire `Contract` instance, which I didn't comment or leave here, and honestly can't remember at this point. We can push forward with using the `Contract` instance, but if I can remember or find the "why" again, I may raise this idea again!

**Pull request merged**
