### PR TITLE
Adjusting codegen script

### PR DESCRIPTION
**Pull request by dafuga**

### CODE REVIEW

**Comment by aaroncox** [comment]
Just FYI - the `action-typings` branch is now part of `dev`, so I swapped which branch this would merge into. Seems to have caused a couple conflicts.

**Comment by dafuga** [comment]
@aaroncox Thanks! I don't see any conflicts, but the checks are failing for some reason 🤔 It's weird, because running `make check` works fine locally. Any idea what's up with that? Apart from that, I think this PR is in a good place and could use a review from you 😄

**Comment by aaroncox** [comment]
Scroll down to the bottom of the PR. You might need to rebase your branch off of `dev` or start a new branch based on `dev` and then cherry pick the commits from this branch.

**Comment by dafuga** [comment]
Oh yeah, I needed to reload the page 😅

**Review by aaroncox — APPROVED** [review]

**Pull request merged**
